<a href="https://colab.research.google.com/github/MohammadrezaPourreza/DataAnalysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

creating arrays

In [6]:
arr = np.array([1,2,3,4]) #array from a list
#or
arr = np.zeros(4)
arr = np.ones(4)
arr = np.random.random(4)
arr

array([0.78717335, 0.11692307, 0.94030399, 0.08633693])

Array arithmetic

In [8]:
data = np.array([1,2,3])
ones =  np.ones(3)
#add + , subtract - , multiply * , division /
arr =  data + ones
arr = data * 1.6 #this is called broadcasting
arr

array([1.6, 3.2, 4.8])

slices

In [9]:
arr[1:2]

array([3.2])

In [10]:
arr[1:]

array([3.2, 4.8])

In [14]:
arr[:-1]

array([1.6, 3.2])

aggregation functions

In [15]:
data.min()

1

In [16]:
data.max()

3

In [17]:
data.mean()

2.0

In [19]:
data.sum()

6

In [20]:
data.prod() #multiply all the elements

6

In [41]:
data = np.array([-1,0,1,2])
data.std() #standard deviation

1.118033988749895

More than one dimension

In [35]:
matrix = np.array([[1,2],[3,4]])
matrix = np.ones((4,3))
matrix1 = np.zeros((4,3))
matrix2 = np.random.random((4,3))
matrix2

array([[0.29747759, 0.12373855, 0.54438453],
       [0.34583132, 0.09444839, 0.82308965],
       [0.16451192, 0.62398954, 0.16336278],
       [0.36738683, 0.68211734, 0.16060033]])

position wise arthimetics (+,-,*,/) for matrices in same size

In [34]:
matrix2 + matrix

array([[1.4429133 , 1.69111216, 1.00695479],
       [1.78335309, 1.68267964, 1.69256864],
       [1.90120894, 1.37399215, 1.89057711],
       [1.85028579, 1.14204439, 1.44820684]])

Broadcasting

In [36]:
matrix *3 

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [38]:
matrix * np.array([1,4,3])

array([[1., 4., 3.],
       [1., 4., 3.],
       [1., 4., 3.],
       [1., 4., 3.]])

In [39]:
matrix * np.array([[1],[2],[3],[4]])

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

Dot product

In [42]:
data.dot(matrix)

array([2., 2., 2.])

In [44]:
matrix2[0:2,2]

array([0.54438453, 0.82308965])

aggregate matrices

In [45]:
#same as vectors mentioned above except we can choose axis
matrix2

array([[0.29747759, 0.12373855, 0.54438453],
       [0.34583132, 0.09444839, 0.82308965],
       [0.16451192, 0.62398954, 0.16336278],
       [0.36738683, 0.68211734, 0.16060033]])

In [47]:
matrix2.max(axis=0) #0 is equal to columns

array([0.36738683, 0.68211734, 0.82308965])

In [48]:
matrix2.prod(axis=1) #1 is equal to rows

array([0.02003849, 0.02688475, 0.0167698 , 0.04024659])

get the transpose of a matrix

In [49]:
matrix2.T

array([[0.29747759, 0.34583132, 0.16451192, 0.36738683],
       [0.12373855, 0.09444839, 0.62398954, 0.68211734],
       [0.54438453, 0.82308965, 0.16336278, 0.16060033]])

**reshaping**

In [50]:
matrix2

array([[0.29747759, 0.12373855, 0.54438453],
       [0.34583132, 0.09444839, 0.82308965],
       [0.16451192, 0.62398954, 0.16336278],
       [0.36738683, 0.68211734, 0.16060033]])

In [51]:
matrix2.reshape(2,6)

array([[0.29747759, 0.12373855, 0.54438453, 0.34583132, 0.09444839,
        0.82308965],
       [0.16451192, 0.62398954, 0.16336278, 0.36738683, 0.68211734,
        0.16060033]])

In [ ]:
#or we can use -1 to automatically find the dimension

In [52]:
matrix2.reshape(6,-1)

array([[0.29747759, 0.12373855],
       [0.54438453, 0.34583132],
       [0.09444839, 0.82308965],
       [0.16451192, 0.62398954],
       [0.16336278, 0.36738683],
       [0.68211734, 0.16060033]])

3D

In [57]:
ndarr = np.ones((4,3,2)) #4 rows 3 columns 2 channels
ndarr = np.zeros((4,5,2))
ndarr = np.random.random((4,3,2))
ndarr #NumPy’s order for printing n-dimensional arrays is that the last axis is looped over the fastest, while the first is the slowest
#so the below is not right!

array([[[0.25962093, 0.52407858],
        [0.70854955, 0.67561877],
        [0.26049625, 0.85310416]],

       [[0.12265981, 0.02665004],
        [0.09084525, 0.5431356 ],
        [0.54123407, 0.37586569]],

       [[0.09237417, 0.6462324 ],
        [0.10442397, 0.20007725],
        [0.49107804, 0.21368266]],

       [[0.0762178 , 0.257692  ],
        [0.49636557, 0.34994136],
        [0.01533178, 0.97467286]]])

Implementing mean squared error

size attribute contains total number of elements

In [59]:
matrix.size

12

In [70]:
def MSE(predictions,labels):
  return (1/(labels.size)*np.sum(np.square(predictions-labels)))
pred = np.ones((4,3,2))
labels = np.array([1,1,1,0,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
labels = labels.reshape(4,3,2)
MSE(pred,labels)

0.125